-- MySQL Script generated by MySQL Workbench
-- Sat Jul 30 13:02:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BooksDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BooksDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BooksDB` DEFAULT CHARACTER SET utf8 ;
USE `BooksDB` ;

-- -----------------------------------------------------
-- Table `BooksDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BooksDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `authorizationStatus` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BooksDB`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BooksDB`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `tags` VARCHAR(100) NOT NULL,
  `image` TEXT(500) NOT NULL,
  `price` INT NOT NULL,
  `description` TEXT(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BooksDB`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BooksDB`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT(500) NOT NULL,
  INDEX `users_idx` (`id` ASC),
  CONSTRAINT `users`
    FOREIGN KEY (`id`)
    REFERENCES `BooksDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `books`
    FOREIGN KEY (`id`)
    REFERENCES `BooksDB`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
